FROM alpine:3.12

RUN apk update && apk add influxdb libc6-compat openrc && openrc reboot
RUN wget https://dl.influxdata.com/telegraf/releases/telegraf-1.16.3_linux_amd64.tar.gz \
    && tar -xzvf telegraf-1.16.3_linux_amd64.tar.gz && rm telegraf-1.16.3_linux_amd64.tar.gz \
    && mv telegraf-1.16.3 telegraf
COPY telegraf.conf /telegraf.conf
COPY prob.sh /prob.sh
COPY influxdb.conf /etc/influxdb.conf
COPY start.sh /tmp/start.sh
RUN chmod +x /tmp/start.sh

EXPOSE 8086 8088

ENTRYPOINT [ "/tmp/start.sh" ]