FROM alpine:3.12

RUN apk update && apk add influxdb openrc && openrc reboot
# telegraf --update-cache --repository http://git.alpinelinux.org/aports/tree/community/telegraf?h=master --allow-untrusted 
    
RUN mkdir -p /etc/telegraf/

COPY telegraf.conf /etc/telegraf
COPY influxdb.conf /etc/influxdb.conf
COPY start.sh /tmp/start.sh
RUN chmod +x /tmp/start.sh

EXPOSE 8086 8088

ENTRYPOINT [ "/tmp/start.sh" ]