apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps-local
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 35000
        - containerPort: 35001
        - containerPort: 35002
        livenessProbe:
            exec:
              command:
              - /bin/sh
              - /prob.sh
            initialDelaySeconds: 30
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/address-pool: default
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  ports:
  - port: 21
    protocol: TCP
    name: "ftps"
    targetPort: 21
  - port: 10090
    protocol: TCP
    name: "ftps1"
    targetPort: 10090
  - port: 10091
    protocol: TCP
    name: "ftps2"
    targetPort: 10091
  - port: 10092
    protocol: TCP
    name: "ftps3"
    targetPort: 10092
  type: LoadBalancer